### ISSUE TITLE
Only works with one font at a time

### ISSUE THREAD

**Issue by SebastianMeisel** [sdushantha/fontpreview#7] opened 2020-02-08 20:02 UTC
For me the font preview works only for one font. When I want to preview a second font I have to quit and restart the script.

Ubuntu 18.04 
bash 4.4.20

**Comment by sdushantha** [comment] 2020-02-08 20:04
Could you please send a screen recording so that I can see what is happening?

**Comment by SebastianMeisel** [comment] 2020-02-08 20:21
Here it is:



Am Sa., 8. Feb. 2020 um 21:04 Uhr schrieb Siddharth Dushantha <
notifications@github.com>:

**Comment by sdushantha** [comment] 2020-02-08 20:23
Hmm...seems like there is nothing. I think it is not showing up because you replied by email.
![image](https://user-images.githubusercontent.com/27065646/74091575-48435980-4ab9-11ea-8083-62845f9b1dec.png)

**Comment by SebastianMeisel** [comment] 2020-02-08 20:27
I had to zip it, so github accepts it.
[vokoscreen-2020-02-08_21-11-56.zip](https://github.com/sdushantha/fontpreview/files/4175120/vokoscreen-2020-02-08_21-11-56.zip)

**Comment by sdushantha** [comment] 2020-02-08 20:31
Ah okay, now I see what the problem is. 
I have configured  `sxiv` to be floating window. You have it so that it fills to whole screen. The problem here is that when you are quitting `sxiv`, and you arent supposed to do that.

Is it possible to set in your window manager to not have a window full screen?

**Comment by SebastianMeisel** [comment] 2020-02-08 20:33
That's possible. But I have to figure out how. I'll do that tomorrow and
let you know.

Siddharth Dushantha <notifications@github.com> schrieb am Sa., 8. Feb.
2020, 21:31:

**Comment by nilskuehme** [comment] 2020-02-08 22:01
Having same issue using floating window

Video: 
![screenrecord](https://user-images.githubusercontent.com/30463384/74092614-d40fb280-4ac6-11ea-97fd-8d7071f103aa.gif)

i3-gaps: 4.15.0.1
bash: 4.4.12

**Comment by maxdevjs** [comment] 2020-02-08 22:07
Strange..

@nilskuehme do you use Ubuntu or similar?

**Comment by southwindcg** [comment] 2020-02-08 22:22
I'm having the same issue, also with a Ubuntu derivative.
I believe the problem stems from sxiv being an obsolete version in the Ubuntu repos. The next version _after_ the one I have (1.3.2-1) says the following in the change log:

https://github.com/muennich/sxiv
> v24 (October 27, 2017)
> Automatically reload the current image whenever it changes

**Comment by maxdevjs** [comment] 2020-02-08 23:51
For what I read so far in comments/issues, seems to affect `Ubuntu/derivative` distros.

**Comment by linuxclowns** [comment] 2020-02-09 06:08
Having a similar problem on Debian Buster.

Interestingly, when I comment out the reset on FIRST_RUN=false in the if/then loop of main, it works.

**Comment by sdushantha** [comment] 2020-02-09 07:39
@linuxclowns Doesnt commenting out `FIRST_RUN=false` create new sxiv windows?

Since this seems to be an issue on Ubuntu and derivative distros, I think it would be best to have a note in the README stateing that if you use Ubuntu or its a distro that is based on Ubuntu, then you have to manually download and compile `sxiv`.

What are your guys thoughts on this?

**Comment by nilskuehme** [comment] 2020-02-09 09:02
@maxdevjs no i do use Debian.

**Comment by sdushantha** [comment] 2020-02-09 09:07
@nilskuehme Well, Ubuntu is based on Debian, so it might be an issue with all Debian based distros

**Comment by SebastianMeisel** [comment] 2020-02-09 09:34
I would recommend to change line 113 to:

        if [ $FIRST_RUN == true || ! -z $(ps -o pid= -p $(cat $PIDFILE)) ]; then

That checks if sxvi is still running and else restarts it. Seems a good idea anyway. Works for me.

**Comment by SebastianMeisel** [comment] 2020-02-09 10:01
Of course it's rather:

 if [ $FIRST_RUN == true ] || [ ! -z $(ps -o pid= -p $(cat $PIDFILE)) ]; then

Sorry for the typo.

**Comment by sdushantha** [comment] 2020-02-09 10:17
@SebastianMeisel Hmmm.... not sure if it is working as intended
![image](https://user-images.githubusercontent.com/27065646/74100286-634fb100-4b2d-11ea-8170-605f71ee4103.png)

**Comment by SebastianMeisel** [comment] 2020-02-09 10:19
Yes, after more testing I run into issues too. Will further try to find
a solution in that direction. I'll test better before answering again...


Am So., 9. Feb. 2020 um 11:17 Uhr schrieb Siddharth Dushantha <
notifications@github.com>:

**Comment by SebastianMeisel** [comment] 2020-02-09 10:39
Could you test this? It seems to work, when sxvi is crashing, but I can't test, if it works if sxvi keeps running:

       if [ $FIRST_RUN == true ] ; then
            FIRST_RUN=false

            # Display the font preview using sxiv
            sxiv -g "$SIZE$POSITION" "$FONT_PREVIEW" -N "fontpreview" -b &

            # Change focus from sxiv, back to the terminal window
            # so that user can continue to search for fonts without
            # having to manually change focus back to the terminal window
            xdotool windowfocus "$(cat "$TERMWIN_IDFILE")"

            # Save the process ID so that we can kill
            # sxiv when the user exits the script
            echo $! >"$PIDFILE"
	 elif [ -f $PIDFILE ] && ! PID=$(cat $PIDFILE) [ -n "$PID" -a -e /proc/$PID ] ; then
		 echo "Restart sxvi - You maybe using a obsolete version. " >&2
		 # Display the font preview using sxiv
		 sxiv -g "$SIZE$POSITION" "$FONT_PREVIEW" -N "fontpreview" -b &

		 # Change focus from sxiv, back to the terminal window
		 # so that user can continue to search for fonts without
		 # having to manually change focus back to the terminal window
		 xdotool windowfocus "$(cat "$TERMWIN_IDFILE")"

		 # Save the process ID so that we can kill
		 # sxiv when the user exits the script
		 echo $! >"$PIDFILE"
    	fi

**Comment by sdushantha** [comment] 2020-02-09 10:52
@SebastianMeisel  Same issue...
![image](https://user-images.githubusercontent.com/27065646/74100724-2df99200-4b32-11ea-85ef-e4651e4f8de0.png)

And here is the code that I added:
![image](https://user-images.githubusercontent.com/27065646/74100764-93e61980-4b32-11ea-8588-d8c9169b42db.png)

**Comment by SebastianMeisel** [comment] 2020-02-09 10:59
Last try: 


            # Save the process ID so that we can kill
            # sxiv when the user exits the script
            echo $! >"$PIDFILE"
	 elif [ -f $PIDFILE ] ; then
		 PID=$(cat $PIDFILE)
		 ls -1 /proc/$PID >&2
		 if  [ ! -e /proc/$PID ] ; then
			 echo "Restart sxvi - You maybe using a obsolete version. " >&2
			 # Display the font preview using sxiv
			 sxiv -g "$SIZE$POSITION" "$FONT_PREVIEW" -N "fontpreview" -b &

			 # Change focus from sxiv, back to the terminal window
			 # so that user can continue to search for fonts without
			 # having to manually change focus back to the terminal window
			 xdotool windowfocus "$(cat "$TERMWIN_IDFILE")"

			 # Save the process ID so that we can kill
			 # sxiv when the user exits the script
			 echo $! >"$PIDFILE"
		 fi
    	fi

**Comment by sdushantha** [comment] 2020-02-09 11:04
@SebastianMeisel Yay it works! Looks like your last try was the best try :blush: 
Could you make a PR for this?

**Comment by SebastianMeisel** [comment] 2020-02-09 13:20
I'll do it tonight (UTC+1;-)

Siddharth Dushantha <notifications@github.com> schrieb am So., 9. Feb.
2020, 12:04:

**Comment by sdushantha** [comment] 2020-02-09 19:42
This has been fixed in version 1.0.2, #21

**Closed by sdushantha** 2020-02-09 19:42 UTC
Labels: bug
